import * as functions from "firebase-functions";
import express from "express";
import cartItemsRouter from "./routes/cartItemsRouter";
import productsRouter from "./routes/productsRouter";
import usersRouter from "./routes/usersRouter";
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/", cartItemsRouter);
app.use("/", usersRouter);
app.use("/", productsRouter);
export const api = functions.https.onRequest(app);
